version: '3.3'

services:

  nginx_site:
    image: nginx:stable-alpine
    container_name: ${DOCKER_CONTAINER_PREFIX}_nginx_site
    volumes:
      - ./configs/nginx/site:/etc/nginx/conf.d/
      - ./${DOCKER_BACKEND_SITE}:/var/www/back
    command: [nginx-debug, '-g', 'daemon off;']
    links:
      - php_fpm_site:php_fpm_site
    depends_on:
      - php_fpm_site
    networks:
      proxy_net:
        ipv4_address: ${DOCKER_HOST_NGINX_SITE}

  nginx_wh:
    image: nginx:stable-alpine
    container_name: ${DOCKER_CONTAINER_PREFIX}_nginx_wh
    volumes:
      - ./configs/nginx/wh:/etc/nginx/conf.d/
      - ./${DOCKER_BACKEND_WH}:/var/www/back
    command: [nginx-debug, '-g', 'daemon off;']
    links:
      - php_fpm_wh:php_fpm_wh
    depends_on:
      - php_fpm_wh
    networks:
      proxy_net:
        ipv4_address: ${DOCKER_HOST_NGINX_WH}

  php_fpm_site:
    image: ${DOCKER_IMAGE_PREFIX}_php_fpm:${DOCKER_TAG}
    container_name: ${DOCKER_CONTAINER_PREFIX}_php_fpm_site
    build:
      context: ./configs/php_fpm/
      dockerfile: Dockerfile
    volumes:
      - ./${DOCKER_BACKEND_SITE}:/var/www/back
    extra_hosts:
      - "weater_history.loc:10.10.77.18"
    links:
      - mysql:mysql
      - redis:redis
    depends_on:
      - mysql
      - redis
    environment:
      - PHP_IDE_CONFIG=serverName=server
    networks:
      proxy_net:
        ipv4_address: ${DOCKER_HOST_PHP_FPM_SITE}

  php_fpm_wh:
    image: ${DOCKER_IMAGE_PREFIX}_php_fpm:${DOCKER_TAG}
    container_name: ${DOCKER_CONTAINER_PREFIX}_php_fpm_wh
    build:
      context: ./configs/php_fpm/
      dockerfile: Dockerfile
    volumes:
      - ./${DOCKER_BACKEND_WH}:/var/www/back
    extra_hosts:
      - "site.loc:10.10.77.15"
    links:
      - mysql:mysql
      - redis:redis
    depends_on:
      - mysql
      - redis
    environment:
      - PHP_IDE_CONFIG=serverName=server
    networks:
      proxy_net:
        ipv4_address: ${DOCKER_HOST_PHP_FPM_WH}

  redis:
    image: redis:6.0-rc-alpine3.11
    container_name: ${DOCKER_CONTAINER_PREFIX}_redis
    networks:
      proxy_net:
        ipv4_address: ${DOCKER_HOST_REDIS}

  mysql:
    image: mysql
    container_name: ${DOCKER_CONTAINER_PREFIX}_mysql
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--innodb_use_native_aio=0',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      proxy_net:
        ipv4_address: ${DOCKER_HOST_MYSQL}

networks:
  proxy_net:
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET}
